name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]  # Only test on the latest Node.js

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack and install correct Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate
          echo "Using Yarn version: $(yarn --version)"

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Verify Yarn version
        run: yarn --version  # Should output 4.6.0

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run build
        run: yarn run build

      - name: Run tests
        run: yarn run test
